version: '3'
services:
  redis:
    image: redis:7.2 # 7.4 will become non-BSD license
    ports:
      - 6379:6379
    command: redis-server --requirepass ${REDIS_PASSWORD}
    env_file:
      .env
  manager:
    image: job_manager
    build: .
    ports:
      - 4503:4503
    depends_on:
      - redis
    env_file:
      .env
    network_mode: host
    command: python3 -u manager.py